apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: longpoll
      app.kubernetes.io/instance: longpoll
      app.kubernetes.io/name: longpoll
