apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: envoy-config
    files:
      - files/envoy.yaml
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: envoy
      app.kubernetes.io/instance: envoy
      app.kubernetes.io/name: envoy
